// Upper bounds for the rank 8 local algebras at 2, 5 and 7 generated by
// the solutions to the standard GFE with signature (2,5,7)

// Load this file from the main folder
AttachSpec("spec");

Q2 := pAdicField(2,500);
Q22 := UnramifiedExtension(Q2,2);
_<t> := PolynomialRing(Q2);
_<t2> := PolynomialRing(Q22);

U2 := [ EtaleAlgebra((t^5 - 2) * (t^3 - 2)),
	EtaleAlgebra(DefiningPolynomial(ext<Q22 | t2^4 + 2*t2^3 + 2*t2^2 + 2>,Q2)),
	DirectProduct(EtaleAlgebra(t^4 + 2*t^3 + 2*t^2 + 2),EtaleAlgebra(t^4 + 2*t^3 + 2*t^2 + 2)),
	EtaleAlgebra(t^8 + 2*t^7 + 2),
	EtaleAlgebra(t^8 + 2*t^7 + 6),
	EtaleAlgebra([UnramifiedExtension(Q2,d) : d in [6,2]]),
	EtaleAlgebra([UnramifiedExtension(Q2,d) : d in [3,3,1,1]]) ];

Q5 := pAdicField(5,500);
_<t> := PolynomialRing(Q5);

U5 := [
	EtaleAlgebra((t^4 - 5) * (t^2 - 10) * t * (t+1)),
	EtaleAlgebra((t^4 - 10) * (t^2 - 5) * t * (t+1)),
	EtaleAlgebra((t^4 + 10) * (t^2 - 5) * t * (t+1)) ] cat
  [ EtaleAlgebra((t^5 - 5*a*t + 5) * (t^2 - 10*a) * t) : a in [1,2,3] ] cat
  [ EtaleAlgebra((t^5 + 5*t + 5) * (t^2 - 10) * t),
	EtaleAlgebra((t^4 + 5) * (t^2 - 10) * t * (t+1)),
	EtaleAlgebra((t^6 - 5) * (t^2 - 10)),
	EtaleAlgebra((t^6 - 10) * (t^2 - 5)),
	EtaleAlgebra((t^7 - 5) * t) ];

Q7 := pAdicField(7,500);
_<t> := PolynomialRing(Q7);

U7 :=
  [ EtaleAlgebra((t^6 + a*7) * t * (t+1)) : a in [1,2,4] ] cat
  [ EtaleAlgebra((t^7 + 7*a*t + 7) * t) : a in [1,2,4] ] cat
  [ EtaleAlgebra((t^5 - 7) * (t^2 - 7) * t),
	EtaleAlgebra(t^8 - 7),
	EtaleAlgebra((t^6 + 7) * t * (t+1)),
	EtaleAlgebra((t^7 + 7*t + 7) * t) ];