// Upper bounds for the rank 8 local algebras at 2, 5 and 7 generated by
// the solutions to the standard GFE with signature (2,5,7)

// Load this file from the main folder
AttachSpec("spec");

Q2 := pAdicField(2,500);

U2 := [ EtaleAlgebra([UnramifiedExtension(Q2,d) : d in P], Q2) :
	P in [[4,2,1],[3,3,1]] ];

Q3 := pAdicField(3,500);
Q32 := UnramifiedExtension(Q3,2);
_<t> := PolynomialRing(Q3);
_<t2> := PolynomialRing(Q32);
a := Roots(t2^2 + 1)[1,1];
b := Roots(t2^2 + 2*t2 + 2)[1,1];

U3 := [
	EtaleAlgebra(t * DefiningPolynomial(ext<Q32 | t2^3 - 3*a*t2 + 3>, Q3)),
	EtaleAlgebra(t * DefiningPolynomial(ext<Q32 | t2^3 + 12*t2^2 + (18*b + 30)*t2 + (12*b + 3)>, Q3)),
	EtaleAlgebra(t * (t^6 - 3*t^2 - 6*t - 3)),
	EtaleAlgebra(t * (t^6 + 3*t^2 + 6*t + 3)),
	EtaleAlgebra(t^7 - 3),
	EtaleAlgebra(t * (t+1) * (t^5 - 3)),
	EtaleAlgebra(t * (t+1) * (t^2 - 3) * (t^3 + 3*t + 3)),
	EtaleAlgebra(t * (t+1) * (t+2) * (t^2 - 3) * (t^2 + 3))];

Q5 := pAdicField(5,500);
_<t> := PolynomialRing(Q5);

U5 := [
	EtaleAlgebra(t * (t^2 - 10) * (t^4 - 5)),
	EtaleAlgebra(t * (t^2 - 10) * (t^4 + 5)),
	EtaleAlgebra((t^2 - 10) * (t^5 + 5*t + 5)),
	EtaleAlgebra((t^2 - 10) * (t^5 + 20*t + 5)),
	EtaleAlgebra((t^2 - 10) * ((t+1)^2 - 10) * (t^3 - 5)),
	EtaleAlgebra(t^7 - 5)];

Q7 := pAdicField(7,500);
_<t> := PolynomialRing(Q7);

U7 := [ EtaleAlgebra(t * (t^6 + 7*a)) : a in [1,2,4] ] cat
	[ EtaleAlgebra(t^7 + 7*a*t + 7) : a in [1,2,4] ] cat
	[ EtaleAlgebra((t^4 - 7) * (t^3 - 7*a)) : a in [1,2,4] ] cat
	[ EtaleAlgebra((t^5 - 7) * (t^2 - 7)) ];
