// Local covering sets for the rank 7 local algebras at 2, 3, 5 and 7 generated by
// the solutions to the standard GFE with signature (2,5,7)

// Load this file from the main folder
AttachSpec("spec");

K<a> := QuadraticField(21);

p2 := Decomposition(K,2)[1,1];
K2 := Completion(K,p2);
K2P := ChangePrecision(K2,500); 
_<t> := PolynomialRing(K2P);

r := Roots(t^2 + 3)[1,1];
U2 :=
	[ EtaleAlgebra((t^2 + 1) * (t^2 - r) * ((t+1)^2 - r) * t),
		EtaleAlgebra((t^2 + 1) * (t^2 - (2+r)) * ((t+1)^2 - (2+r)) * t),
		EtaleAlgebra(t^7 - 2)	];


p3 := Decomposition(K,3)[1,1];
K3,phi3 := Completion(K,p3);
K3P := ChangePrecision(K3,500);
phi3P := Coercion(K3,K3P);
_<t> := PolynomialRing(K3P);

U3 := [ EtaleAlgebra(t^7 - phi3P(phi3(a))) ];


p51 := Decomposition(K,5)[1,1];
K51 := Completion(K,p51);
K51P := ChangePrecision(K51,500);
_<t> := PolynomialRing(K51P);
U51 :=
	[ EtaleAlgebra((t^4 + 5) * (t^2 - 10) * t),
		EtaleAlgebra((t^5 + 5*t + 5) * (t^2 - 10)) ];


p52 := Decomposition(K,5)[2,1];
K52 := Completion(K,p52);
K52P := ChangePrecision(K52,500);
_<t> := PolynomialRing(K52P);
U52 :=
	[ EtaleAlgebra((t^4 + 5) * (t^2 - 10) * t),
		EtaleAlgebra((t^5 + 5*t + 5) * (t^2 - 10)) ];


p7 := Decomposition(K,7)[1,1];
K7 := Completion(K,p7);
K7P := ChangePrecision(K7,500);
_<t> := PolynomialRing(K7P);
U7 :=
	[ EtaleAlgebra((t^3 - 7) * ((t+1)^3 - 7) * t),
		EtaleAlgebra(t^7 + 7*t + 7) ];
